version: '3'

services:
  db:
    image: postgres:latest
    hostname: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "5432:5432"
  web:
    build: .
    command: bash -c "python ./myproject/manage.py migrate --noinput && python ./myproject/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/myproject/web
    ports:
      - "8000:8000"
    depends_on:
      - db   
  redis:
    image: redis:alpine
  celery:
    build: .
    command: bash -c "cd ./myproject && celery -A myproject worker -l info"
    volumes:
      - .:/code
    depends_on:
      - web
      - db
      - redis

volumes:
  postgres_data:

