# Generated by Django 3.0.3 on 2020-02-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urltags',
            name='url',
            field=models.URLField(max_length=400),
        ),
    ]
